config/routes.rb
Demo::Application.routes.draw do
  get "home/index"

  resources :photos
  resources :products
  resources :errorhandler

  root :to => 'islands#index'

  
  match '/islands' => 'islands#listing'
  match '/islands/:id' => 'islands#show'
  match '/contact' => 'home#contact'
  match '/about' => 'home#about'
  
  match "*path" => 'errorhandler#show'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :active, :alttxt, :filename, :order, :product_id, :caption
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :active, :details, :price, :stock, :summary, :title, :featured, :title_photo
  has_many :photos
  
  def short_summary(limit)
	return self.summary[0,limit]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/errorhandler_controller.rb
class ErrorhandlerController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	allItems = Product.all
	@islands = Array.new
	@featured = Array.new
	for i in Product.all
		if i.active
			@islands.push(i)
			if i.featured != nil && i.featured > 0
				@featured.push(i)
			end
		end
	end 
	
	@islands.sort! {|i,k| i.title<=>k.title}
	@featured.sort! {|i,k| i.featured<=>k.featured}
	
	#@islands = Product.find(:all, :conditions=> :order=>"title")
	#@featured = Product.find(:all, :order=>"featured")
  end
  
  def contact
  end
  def about
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  def _get_active_islands
    return Product.all.select{ |i| i.active == true }
  end

  # GET /products
  # GET /products.json
  def index
	allItems = Product.all
	@islands = Array.new
	@featured = Array.new
	for i in Product.all
		if i.active
			@islands.push(i)
			if i.featured != nil && i.featured > 0
				@featured.push(i)
			end
		end
	end 
	
	@islands.sort! {|i,k| i.title<=>k.title}
	@featured.sort! {|i,k| i.featured<=>k.featured}
	
	#@islands = Product.find(:all, :conditions=> :order=>"title")
	#@featured = Product.find(:all, :order=>"featured")
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @island = Product.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @island }
    end
  end
  
  def _sort_by_params (collection)
	# summary
	if params[:sort] == 's'
		collection.sort! {|i,k| i.summary<=>k.summary}
	end
	if params[:sort] == 'S'
		collection.sort! {|k,i| i.summary<=>k.summary}
	end
	
	# name
	if params[:sort] == 'n'
		collection.sort! {|i,k| i.title<=>k.title}
	end
	if params[:sort] == 'N'
		collection.sort! {|k,i| i.title<=>k.title}
	end
	
	# price
	if params[:sort] == 'p'
		collection.sort! {|i,k| i.price<=>k.price}
	end
	if params[:sort] == 'P'
		collection.sort! {|k,i| i.price<=>k.price}
	end
	
	return collection
  end
  
  def listing
    @islands = _sort_by_params(_get_active_islands)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, :notice => 'Photo was successfully created.' }
        format.json { render :json => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, :notice => 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, :notice => 'Product was successfully created.' }
        format.json { render :json => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, :notice => 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errorhandler_helper.rb
module ErrorhandlerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/islands_helper.rb
module IslandsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/errorhandler/show.html.erb
<h1>Sorry!  Could not find the page you were looking for</h1>
<a href="/">Click here to return to the main site</a>

app/views/home/_icon_item.erb
<% summary_limit = 100 %>
<% has_photo = island.title_photo != nil && island.title_photo.length > 0 %>
	<table class="icon_item">
	<tr>
		<% if has_photo %>
			<td><img src="/product_img/<%= island.title_photo %>" class="title_photo" /></td>
		<% end %>
		<td style="vertical-align:top;">
			<p class="title"><a href="/islands/<%= island.id %>"><%= island.title %></a></p>
			<p class="price"><%= number_to_currency(island.price, :unit => '$') %><p>
		<% if has_photo %>
			</td>
			<tr>
			<td colspan="2">
		<% end %>
			<p class="summary"><%= island.short_summary(summary_limit) %><%= island.summary.length > summary_limit ? " ... " : "" %></p>
		</td>
	</tr>
	</table>
<% end %>

app/views/home/about.html.erb
You want to know about us?  You probably don't, we're not that cool.  This page is just here to show that we can create an "About Us" page.  Sorry if this was a tease.

app/views/home/contact.html.erb
Contact us!

Please contact us at woot_contact@totallyradislands.com

app/views/home/index.html.erb
<h1>Check out these islands!</h1>

<% row_limit = 3 %>

<% if @featured.count > 0 %>
	<% grid_counter = 0 %>
	<h2>Featured</h2>
	<table class="grid_table">
	<% @featured.each do |i| %>
		<% if grid_counter % row_limit == 0 %>
			<tr>
		<% end %>
		<td class="grid_item"><%= render 'icon_item', :island => i %></td>
		<% if (grid_counter + 1) % row_limit == 0 %>
			</tr>
		<% end %>
		<% grid_counter = grid_counter + 1 %>
	<% end %>
	</table>
<% end %>

<% if @islands.count > 0 %>
	<% grid_counter = 0 %>
	<h2>Other Islands for Sale</h2>
	<table class="grid_table">
	<% @islands.each do |i| %>
		<% if grid_counter % row_limit == 0 %>
			<tr>
		<% end %>
		<td class="grid_item"><%= render 'icon_item', :island => i %></td>
		<% if (grid_counter + 1) % row_limit == 0 %>
			</tr>
		<% end %>
		<% grid_counter = grid_counter + 1 %>
	<% end %>
	</table>
<% end %>

<p><%= link_to "Products", islands_path %>!</p>
<p><%= link_to "Photos", photos_path %></p>

app/views/islands/_icon_item.erb
<% summary_limit = 100 %>
<% has_photo = island.title_photo != nil && island.title_photo.length > 0 %>
<table class="icon_item">
<tr>
	<% if has_photo %>
		<td class="photo"><a href="/islands/<%= island.id %>"><img src="/product_img/<%= island.title_photo %>" class="title_photo" /></a></td>
	<% end %>
	<td style="vertical-align:top;">
		<p class="title"><a href="/islands/<%= island.id %>"><%= island.title %></a></p>
		<p class="price"><%= number_to_currency(island.price, :unit => '$') %><p>
	<% if has_photo %>
		</td>
		<tr>
		<td colspan="2">
	<% end %>
		<p class="summary"><%= island.short_summary(summary_limit) %><%= island.summary.length > summary_limit ? " ... " : "" %></p>
	</td>
</tr>
</table>

app/views/islands/_listing_item.erb
<% summary_limit = 200 %>
<% if island != nil %>
<tr class="row_<%= counter % 2 == 0 ? 'a' : 'b' %>">
	<td class="title"><a href="/islands/<%= island.id %>"><%=island.title%></a></td>
	<td class="photo">
		<% if island.title_photo != nil && island.title_photo.length > 0 %>
			<a href="/islands/<%= island.id %>"><img src="/product_img/<%= island.title_photo %>" class="title_photo" /></a>
		<% end %>
	</td>
	<td class="summary"><%= island.short_summary(summary_limit) %><%= island.summary.length > summary_limit ? " ... " : "" %></td>
	<td class="price"><%= number_to_currency(island.price, :unit=>'$') %></td>
</tr>
<% end %>

app/views/islands/index.html.erb
<% row_limit = 3 %>

<% if @featured.count > 0 %>
	<% grid_counter = 0 %>
	<h2>Featured</h2>
	<table class="grid_table">
	<% @featured.each do |i| %>
		<% if grid_counter % row_limit == 0 %>
			<tr>
		<% end %>
		<td class="grid_item"><%= render 'icon_item', :island => i %></td>
		<% if (grid_counter + 1) % row_limit == 0 %>
			</tr>
		<% end %>
		<% grid_counter = grid_counter + 1 %>
	<% end %>
	</table>
<% end %>

<% if @islands.count > 0 %>
	<% grid_counter = 0 %>
	<h2>Other Islands for Sale</h2>
	<table class="grid_table">
	<% @islands.each do |i| %>
		<% if grid_counter % row_limit == 0 %>
			<tr>
		<% end %>
		<td class="grid_item"><%= render 'icon_item', :island => i %></td>
		<% if (grid_counter + 1) % row_limit == 0 %>
			</tr>
		<% end %>
		<% grid_counter = grid_counter + 1 %>
	<% end %>
	</table>
<% end %>

app/views/islands/listing.html.erb
<% if @islands != nil && @islands.count > 0 %>
	<h2>All islands</h2>
	<table class="listing_table">
	<tr>
		<th><a href="?sort=<%= params[:sort]=='n' ? 'N' : 'n' %>">Name</a>
			<% if params[:sort] != nil && params[:sort].downcase == 'n' %>
				<span class="sorting_arrow">
				<img src="/img/<%= params[:sort] == 'n' ? 'sorting_arrow_down' : 'sorting_arrow_up' %>.gif" />
				</span>
			<% end %>
		</th>
		<th></th>
		<th><a href="?sort=<%= params[:sort]=='s' ? 'S' : 's' %>">Summary</a>
			<% if params[:sort] != nil && params[:sort].downcase == 's' %>
				<span class="sorting_arrow">
				<img src="/img/<%= params[:sort] == 's' ? 'sorting_arrow_down' : 'sorting_arrow_up' %>.gif" />
				</span>
			<% end %>
		</th>
		<th><a href="?sort=<%= params[:sort]=='p' ? 'P' : 'p' %>">Price</a>
			<% if params[:sort] != nil && params[:sort].downcase == 'p' %>
				<span class="sorting_arrow">
				<img src="/img/<%= params[:sort] == 'p' ? 'sorting_arrow_down' : 'sorting_arrow_up' %>.gif" />
				</span>
			<% end %>
		</th>
	</tr>
	<% counter = 0 %>
	<% @islands.each do |i| %>
		<%= render 'listing_item', :island => i, :counter => counter %>
		<% counter = counter + 1 %>
	<% end %>
	</table>
<% end %>

app/views/islands/show.html.erb
<table class="island_detail"><tr>
<td class="main_section">
<h2><%= @island.title %></h2>

<div class="stats_text">
	<p><label>Price:</label> <%= number_to_currency(@island.price, :unit=>'$') %></p>
	<p><label>Stock:</label> only <%= @island.stock %> left!</p>
</div>

<% if @island.summary != nil && @island.summary.length > 0 %>
<div class="summary_text">
	<%= @island.summary %>
</div>
<% end %>

<% if @island.details != nil && @island.details.length > 0 %>
<h3>Details</h3>
<div class="details_text">
	<%= raw(@island.details) %>
</div>
<% end %>
</td>

<% if @island.photos != nil && @island.photos.count > 0 %>
	<td class="photos">
	
	<% @island.photos.each do |photo| %>
		<% if photo.active %>
			<div class="photo">
				<img src="/product_img/<%= photo.filename %>" alt="<%= photo.alttxt %>" title="<%= photo.alttxt %>" width="300px" />
				<% if photo.caption != nil && photo.caption.length > 0 %>
					<br />
					<%= photo.caption %>
				<% end %>
			</div>
		<% end %>
	<% end %>
	
	</td>
<% end %>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<table class="pageTable">
<tr>
<td colspan="2" style="height:100px;">
<h1><a href="/">Dave's Totally Awesome Islands for Sale</a></h1>
<b>Check out these totally rad islands!!!</b>
</td>
</tr>
<tr>
<td class="leftNav">
	<p><a href="/">Home</a></p>
	<p><a href="/islands">Islands</a></p>
	<p><a href="/contact">Contact Us</a></p>
	<p><a href="/about">About Us</a></p>
</td>
<td class="mainWindow">
	<%= yield %>
</td>
</tr>
<tr>
	<td colspan=2 class="footer">
	This is a fake website and we do not under any circumstance sell islands.  Although that would be awesome.  If you or anyone else owns an island and would like for us to sell it, we'd be more than happy to in exchange for massive, massive profits.  Or candy.  Guess what?  This is a footer.
	</td>
</tr>
</table>

</body>
</html>

app/views/layouts/errorhandler.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alttxt %><br />
    <%= f.text_field :alttxt %>
  </div>
  <div class="field">
    <%= f.label :filename %><br />
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<div style="width:340px; border:1px solid black;">
<img src="/product_img/<%= @photo.filename %>" width="300px" alt="<%= @photo.alttxt %>" title="<%= @photo.alttxt %>" />
<br />
<%= @photo.caption %>
</div>
<br/>
Product: <%= Product.find(@photo.product_id) != nil ? Product.find(@photo.product_id).title : "(none)" %><br><br>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Alttxt</th>
    <th>Filename</th>
    <th>Product</th>
    <th>Active</th>
    <th>Order</th>
    <th>Caption</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% counter = 0 %>
<% @photos.each do |photo| %>
  <tr class="row_<%= counter % 2 == 1 ? 'a' : 'b' %>">
    <td><%= photo.alttxt %></td>
    <td><%= photo.filename %></td>
    <td><%= photo.product_id %></td>
    <td><%= photo.active %></td>
    <td><%= photo.order %></td>
    <td><%= photo.caption %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
  <% counter = counter + 1 %>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Alttxt:</b>
  <%= @photo.alttxt %>
</p>

<p>
  <b>Filename:</b>
  <%= @photo.filename %>
</p>

<p>
  <b>Product:</b>
  <%= @photo.product_id %>
</p>

<p>
  <b>Active:</b>
  <%= @photo.active %>
</p>

<p>
  <b>Order:</b>
  <%= @photo.order %>
</p>

<p>
  <b>Caption:</b>
  <%= @photo.caption %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :stock %><br />
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :title_photo %><br />
    <%= f.text_field :title_photo %>
  </div>
  <div class="field">
    <%= f.label :featured %><br />
    <%= f.text_field :featured %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Active</th>
    <th>Details</th>
    <th>Price</th>
    <th>Stock</th>
    <th>Summary</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.active %></td>
    <td><%= product.details %></td>
    <td><%= product.price %></td>
    <td><%= product.stock %></td>
    <td><%= product.summary %></td>
    <td><%= product.title %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Active:</b>
  <%= @product.active %>
</p>

<p>
  <b>Details:</b>
  <%= @product.details %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Stock:</b>
  <%= @product.stock %>
</p>

<p>
  <b>Summary:</b>
  <%= @product.summary %>
</p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
	<b>Featured Order:</b>
	<%= @product.featured %>
</p>

<p>
	<b>Title Photo:</b><br />
	<img src="/product_img/<%= @product.title_photo %>" width="300px" />
</p>
	

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>